server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - name: InfoFilter
      routes:
        - id: studentRoute 
          uri: lb://student-service 
          predicates: 
            - Path=/students/**
        - id: courseRoute 
          uri: lb://course-service 
          predicates: 
            - Path=/courses/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
info:
  app:
    name: gateway-service
    description: Gateway Service created for Parcial
    version: 1.0.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
